// One-shot generator for sealed_box.json and fingerprint_sig.json.
// Run with: node packages/protocol/test-vectors/regen-crypto.mjs
// after `pnpm install` (libsodium-wrappers must be present).
//
// These vectors are deterministic given the inputs:
//   - Ed25519 sign(msg, sk) is deterministic per RFC 8032
//   - Ed25519 → X25519 conversion is deterministic
//   - sealed box DECRYPT is deterministic; sealed box ENCRYPT is NOT
//     (uses ephemeral keypair, random per call).
//
// Strategy:
//   - fingerprint_sig.json: full byte-match (signed_payload + signature both deterministic)
//   - sealed_box.json: provide pre-sealed ciphertext, test only the decrypt path

import sodium from 'libsodium-wrappers';
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

await sodium.ready;

const __dirname = dirname(fileURLToPath(import.meta.url));
const toHex = (b) => Buffer.from(b).toString('hex');
const fromHex = (h) => new Uint8Array(Buffer.from(h, 'hex'));

// ── Use RFC 8032 test vector seeds for determinism ──
// RFC 8032 §7.1 Test 1
const SEED1 = fromHex('9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60');
// RFC 8032 §7.1 Test 2
const SEED2 = fromHex('4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb');

// crypto_sign_seed_keypair gives the full 64-byte sk (seed || pk)
const kp1 = sodium.crypto_sign_seed_keypair(SEED1);
const kp2 = sodium.crypto_sign_seed_keypair(SEED2);

// ── Sealed box vectors ──
// We pre-seal payloads at generation time and ship the sealed bytes.
// Runner tests the DECRYPT path against these bytes.
const recipientX1 = {
  pk: sodium.crypto_sign_ed25519_pk_to_curve25519(kp1.publicKey),
  sk: sodium.crypto_sign_ed25519_sk_to_curve25519(kp1.privateKey),
};

const sealedShort = sodium.crypto_box_seal(Buffer.from('hello'), recipientX1.pk);
const sealedEmpty = sodium.crypto_box_seal(new Uint8Array(0), recipientX1.pk);
const longPayload = Buffer.alloc(976, 0x41); // 976 bytes of 'A'
const sealedLong = sodium.crypto_box_seal(longPayload, recipientX1.pk);

const sealedBoxVectors = {
  description: "NaCl sealed box test vectors — DECRYPT path only (encrypt is non-deterministic due to ephemeral keypair).",
  note: "Generated by packages/protocol/test-vectors/regen-crypto.mjs. Runner verifies: ed25519→x25519 conversion is deterministic, sealed_box_open with x25519 keypair reproduces the original payload. Encrypt-side determinism is impossible per NaCl design (each seal uses a fresh ephemeral keypair).",
  vectors: [
    {
      name: "decrypt short payload (RFC 8032 key 1)",
      input: {
        ed25519_secret_key_hex: toHex(kp1.privateKey),
        ed25519_public_key_hex: toHex(kp1.publicKey),
        sealed_hex: toHex(sealedShort),
      },
      expected: {
        x25519_public_key_hex: toHex(recipientX1.pk),
        x25519_secret_key_hex: toHex(recipientX1.sk),
        decrypted_utf8: "hello",
        sealed_size: sealedShort.length,
      },
    },
    {
      name: "decrypt empty payload",
      input: {
        ed25519_secret_key_hex: toHex(kp1.privateKey),
        ed25519_public_key_hex: toHex(kp1.publicKey),
        sealed_hex: toHex(sealedEmpty),
      },
      expected: {
        decrypted_utf8: "",
        sealed_size: sealedEmpty.length,
      },
    },
    {
      name: "decrypt max-size payload (976 bytes of 'A')",
      input: {
        ed25519_secret_key_hex: toHex(kp1.privateKey),
        ed25519_public_key_hex: toHex(kp1.publicKey),
        sealed_hex: toHex(sealedLong),
      },
      expected: {
        decrypted_byte: 0x41,
        decrypted_length: 976,
        sealed_size: sealedLong.length, // should be 1024
      },
    },
  ],
};

writeFileSync(resolve(__dirname, 'sealed_box.json'), JSON.stringify(sealedBoxVectors, null, 2) + '\n');
console.log('wrote sealed_box.json:', sealedBoxVectors.vectors.length, 'vectors');

// ── Fingerprint signature vectors ──
// signed_payload = fingerprint(32) || peer_id_bytes(32) || ts_be(8) || nonce(16) = 88 bytes
// Both signed_payload concat and Ed25519 detached signature are deterministic.

function buildPayload(fp, pk, ts, nonce) {
  const tsBytes = new Uint8Array(8);
  new DataView(tsBytes.buffer).setBigUint64(0, BigInt(ts), false);
  const out = new Uint8Array(32 + 32 + 8 + 16);
  out.set(fp, 0); out.set(pk, 32); out.set(tsBytes, 64); out.set(nonce, 72);
  return out;
}

const cases = [
  {
    name: "kp1 + sequential fingerprint + ts=1736937600",
    kp: kp1,
    fingerprint: fromHex('a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2'),
    timestamp: 1736937600,
    nonce: fromHex('0102030405060708090a0b0c0d0e0f10'),
  },
  {
    name: "kp1 + different fingerprint + ts=1737024000",
    kp: kp1,
    fingerprint: fromHex('0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20'),
    timestamp: 1737024000,
    nonce: fromHex('ffeeddccbbaa99887766554433221100'),
  },
  {
    name: "kp2 + zero-fingerprint + ts=0 + zero-nonce (edge case)",
    kp: kp2,
    fingerprint: new Uint8Array(32),
    timestamp: 0,
    nonce: new Uint8Array(16),
  },
];

const fpVectors = {
  description: "Ed25519 fingerprint signature vectors — byte-deterministic (Ed25519 sign is deterministic per RFC 8032).",
  note: "Generated by packages/protocol/test-vectors/regen-crypto.mjs. signed_payload = fingerprint(32) || peer_id(32) || ts_be(8) || nonce(16) = 88 bytes. Runner verifies both the payload concat AND the signature byte-for-byte. RFC 8032 keypairs are used so signatures match across any compliant Ed25519 implementation.",
  vectors: cases.map(c => {
    const payload = buildPayload(c.fingerprint, c.kp.publicKey, c.timestamp, c.nonce);
    const sig = sodium.crypto_sign_detached(payload, c.kp.privateKey);
    return {
      name: c.name,
      input: {
        ed25519_public_key_hex: toHex(c.kp.publicKey),
        ed25519_secret_key_hex: toHex(c.kp.privateKey),
        fingerprint_hex: toHex(c.fingerprint),
        timestamp: c.timestamp,
        nonce_hex: toHex(c.nonce),
      },
      expected: {
        signed_payload_hex: toHex(payload),
        signature_hex: toHex(sig),
      },
    };
  }),
};

writeFileSync(resolve(__dirname, 'fingerprint_sig.json'), JSON.stringify(fpVectors, null, 2) + '\n');
console.log('wrote fingerprint_sig.json:', fpVectors.vectors.length, 'vectors');
